### ISSUE TITLE
CommonChunksPlugin not compatible with karma-webpack

### ISSUE THREAD

**Issue by cskeppstedt** [pirelenito/sagui#12]
According to https://github.com/webpack/karma-webpack/issues/24#issuecomment-113938603 karma-webpack can't handle the CommonsChunkPlugin.

When running `npm run sagui:test`:

```
02 12 2015 08:51:03.749:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
02 12 2015 08:51:03.757:INFO [launcher]: Starting browser PhantomJS
02 12 2015 08:51:06.216:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket Nxvsdn0pA8p8NUMZAAAA with id 2476782
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: webpackJsonp
  at /Users/-snip-/src/index.spec.js:12
```

Removing the plugin from the webpack config seems to allow me to run the tests.

**Comment by pirelenito** [comment]
The commons chunk was introduced on a change yesterday. Sorry about that.

**Comment by pirelenito** [comment]
I'm still missing some "integration" testing to make sure everything works.
